"""
DrugBank-FAERS Match Verification Tool
=======================================
After running ddi_study.py Phase 2, this script lets you inspect and audit
the drug name matches between FAERS and DrugBank.

Usage:
    python verify_drugbank_matches.py                    # full summary + random sample
    python verify_drugbank_matches.py --sample 50        # sample 50 matches
    python verify_drugbank_matches.py --method fuzzy     # inspect only fuzzy matches
    python verify_drugbank_matches.py --search metformin # search for a specific drug
    python verify_drugbank_matches.py --export bad_matches.csv  # export for manual review

Reads: results/ddi_study/phase2_match_details.csv  (generated by Phase 2)
"""

import argparse
import sys
from pathlib import Path

import pandas as pd

DETAILS_PATH = Path("results/ddi_study/phase2_match_details.csv")


def load_details(path: Path = DETAILS_PATH) -> pd.DataFrame:
    if not path.exists():
        print(f"ERROR: {path} not found. Run ddi_study.py --phase 2 first.")
        sys.exit(1)
    df = pd.read_csv(path, dtype=str)
    df["score"] = pd.to_numeric(df["score"], errors="coerce")
    return df


def print_summary(df: pd.DataFrame):
    print("=" * 70)
    print("  DRUGBANK-FAERS MATCH SUMMARY")
    print("=" * 70)
    print(f"  Total matched drugs: {len(df):,}")
    print()
    print("  Match method breakdown:")
    for method, count in df["method"].value_counts().items():
        pct = 100 * count / len(df)
        print(f"    {method:25s}  {count:>6,}  ({pct:.1f}%)")
    print()

    fuzzy = df[df["method"] == "fuzzy"]
    if len(fuzzy) > 0:
        print(f"  Fuzzy matches: {len(fuzzy):,}")
        print(f"    Score range: {fuzzy['score'].min():.0f} - {fuzzy['score'].max():.0f}")
        print(f"    Mean score:  {fuzzy['score'].mean():.1f}")
        print(f"    Median:      {fuzzy['score'].median():.1f}")
        low = fuzzy[fuzzy["score"] < 95]
        print(f"    Below 95:    {len(low):,}  (highest mismatch risk)")
    print("=" * 70)


def print_sample(df: pd.DataFrame, n: int = 30, method: str = None):
    subset = df
    if method:
        subset = df[df["method"] == method]
        if len(subset) == 0:
            print(f"No matches with method '{method}'.")
            return
        print(f"\n--- Sample of '{method}' matches ({len(subset):,} total) ---\n")
    else:
        print(f"\n--- Random sample ({n} of {len(df):,}) ---\n")

    sample = subset.sample(n=min(n, len(subset)), random_state=None)

    cols = ["faers_name", "drugbank_id", "drugbank_name", "method", "score"]
    if "fuzzy_matched_to" in sample.columns:
        cols.append("fuzzy_matched_to")
    present_cols = [c for c in cols if c in sample.columns]

    pd.set_option("display.max_colwidth", 40)
    pd.set_option("display.width", 140)
    print(sample[present_cols].to_string(index=False))
    print()


def print_fuzzy_audit(df: pd.DataFrame, n: int = 50):
    """Show the lowest-confidence fuzzy matches for manual review."""
    fuzzy = df[df["method"] == "fuzzy"].copy()
    if len(fuzzy) == 0:
        print("No fuzzy matches to audit.")
        return

    fuzzy.sort_values("score", inplace=True)
    worst = fuzzy.head(n)

    print(f"\n{'=' * 70}")
    print(f"  LOWEST-CONFIDENCE FUZZY MATCHES (bottom {len(worst)})")
    print(f"{'=' * 70}\n")

    for _, row in worst.iterrows():
        flag = " *** SUSPECT" if row["score"] < 92 else ""
        print(f"  FAERS:     {row['faers_name']}")
        print(f"  DrugBank:  {row.get('drugbank_name', '?')} ({row['drugbank_id']})")
        print(f"  Matched:   {row.get('fuzzy_matched_to', '?')}")
        print(f"  Score:     {row['score']:.0f}{flag}")
        print()


def search_drug(df: pd.DataFrame, query: str):
    """Search for a specific drug name in both FAERS and DrugBank columns."""
    q = query.lower()
    mask = (
        df["faers_name"].str.lower().str.contains(q, na=False) |
        df["drugbank_name"].fillna("").str.lower().str.contains(q, na=False)
    )
    hits = df[mask]
    if len(hits) == 0:
        print(f"No matches found for '{query}'.")
        return

    print(f"\n--- Search results for '{query}' ({len(hits)} hits) ---\n")
    cols = ["faers_name", "drugbank_id", "drugbank_name", "method", "score"]
    if "fuzzy_matched_to" in hits.columns:
        cols.append("fuzzy_matched_to")
    present_cols = [c for c in cols if c in hits.columns]
    pd.set_option("display.max_colwidth", 50)
    pd.set_option("display.width", 150)
    print(hits[present_cols].to_string(index=False))
    print()


def export_for_review(df: pd.DataFrame, path: str, score_cutoff: float = 95):
    """Export matches below a score cutoff for manual review."""
    fuzzy = df[df["method"] == "fuzzy"].copy()
    risky = fuzzy[fuzzy["score"] < score_cutoff].sort_values("score")
    if len(risky) == 0:
        print(f"No fuzzy matches below score {score_cutoff}. Nothing to export.")
        return
    risky.to_csv(path, index=False)
    print(f"Exported {len(risky)} suspect matches to {path}")


def main():
    parser = argparse.ArgumentParser(description="Verify DrugBank-FAERS matches")
    parser.add_argument("--sample", type=int, default=30,
                        help="Number of random matches to display (default: 30)")
    parser.add_argument("--method", type=str, default=None,
                        help="Filter to a specific match method "
                             "(sdf_generic_name, sdf_synonym, sdf_product, "
                             "vocab_common_name, vocab_synonym, fuzzy)")
    parser.add_argument("--search", type=str, default=None,
                        help="Search for a specific drug name")
    parser.add_argument("--audit-fuzzy", action="store_true",
                        help="Show lowest-confidence fuzzy matches")
    parser.add_argument("--export", type=str, default=None,
                        help="Export suspect matches to CSV for manual review")
    parser.add_argument("--score-cutoff", type=float, default=95,
                        help="Score threshold for suspect match export (default: 95)")
    parser.add_argument("--details", type=str, default=str(DETAILS_PATH),
                        help="Path to phase2_match_details.csv")
    args = parser.parse_args()

    df = load_details(Path(args.details))
    print_summary(df)

    if args.search:
        search_drug(df, args.search)
    elif args.audit_fuzzy:
        print_fuzzy_audit(df, n=args.sample)
    elif args.export:
        export_for_review(df, args.export, args.score_cutoff)
    else:
        print_sample(df, n=args.sample, method=args.method)

        fuzzy = df[df["method"] == "fuzzy"]
        if len(fuzzy) > 0:
            print("Tip: Run with --audit-fuzzy to see lowest-confidence matches.")
            print("     Run with --export suspect.csv to export them for review.")


if __name__ == "__main__":
    main()
