"""
DrugBank-FAERS Match Verification Tool
=======================================
After running ddi_study.py Phase 1, this script lets you inspect and audit
the drug name canonicalization between FAERS and DrugBank.

Usage:
    python verify_drugbank_matches.py                    # full summary + random sample
    python verify_drugbank_matches.py --sample 50        # sample 50 matches
    python verify_drugbank_matches.py --matched          # show only matched drugs
    python verify_drugbank_matches.py --unmatched        # show only unmatched drugs
    python verify_drugbank_matches.py --search metformin # search for a specific drug
    python verify_drugbank_matches.py --export review.csv

Reads: results/ddi_study/phase2_match_details.csv  (generated by Phase 1)
"""

import argparse
import sys
from pathlib import Path

import pandas as pd

DETAILS_PATH = Path("results/ddi_study/phase2_match_details.csv")
DBID_NAME_PATH = Path("results/ddi_study/dbid_to_name.json")


def load_details(path: Path = DETAILS_PATH) -> pd.DataFrame:
    if not path.exists():
        print(f"ERROR: {path} not found. Run ddi_study.py first.")
        sys.exit(1)
    df = pd.read_csv(path, dtype=str)
    df["matched"] = df["matched"].map({"True": True, "False": False})
    return df


def load_names() -> dict:
    if DBID_NAME_PATH.exists():
        import json
        with open(DBID_NAME_PATH) as f:
            return json.load(f)
    return {}


def print_summary(df: pd.DataFrame, names: dict):
    n_total = len(df)
    n_matched = df["matched"].sum()
    n_unmatched = n_total - n_matched

    print("=" * 70)
    print("  DRUGBANK-FAERS CANONICALIZATION SUMMARY")
    print("=" * 70)
    print(f"  Total unique FAERS drug names: {n_total:,}")
    print(f"  Mapped to DrugBank ID:         {n_matched:,}  ({100*n_matched/n_total:.1f}%)")
    print(f"  Unmapped:                      {n_unmatched:,}  ({100*n_unmatched/n_total:.1f}%)")

    matched = df[df["matched"]]
    if len(matched) > 0:
        n_unique_ids = matched["drugbank_id"].nunique()
        print(f"\n  Unique DrugBank IDs: {n_unique_ids:,}")
        collapse_ratio = len(matched) / n_unique_ids if n_unique_ids else 0
        print(f"  Name collapse ratio: {collapse_ratio:.2f}x "
              f"({len(matched):,} names -> {n_unique_ids:,} IDs)")

        # Show most-collapsed drugs (many FAERS names -> 1 ID)
        id_counts = matched.groupby("drugbank_id")["faers_name"].count().sort_values(ascending=False)
        multi = id_counts[id_counts > 1]
        if len(multi) > 0:
            print(f"\n  Top collapsed drugs ({len(multi):,} IDs have multiple FAERS names):")
            for dbid, count in multi.head(15).items():
                gname = names.get(dbid, dbid)
                faers_names = matched[matched["drugbank_id"] == dbid]["faers_name"].tolist()
                abbrev = ", ".join(faers_names[:5])
                if len(faers_names) > 5:
                    abbrev += f" ... (+{len(faers_names)-5})"
                print(f"    {gname} ({dbid}): {count} names -> {abbrev}")

    print("=" * 70)


def print_sample(df: pd.DataFrame, names: dict, n: int = 30, matched_only=None):
    subset = df
    if matched_only is True:
        subset = df[df["matched"]]
    elif matched_only is False:
        subset = df[~df["matched"]]

    if len(subset) == 0:
        print("No entries to show.")
        return

    sample = subset.sample(n=min(n, len(subset)), random_state=None)
    sample = sample.copy()
    sample["drugbank_name"] = sample["drugbank_id"].map(lambda x: names.get(x, "") if pd.notna(x) else "")

    pd.set_option("display.max_colwidth", 40)
    pd.set_option("display.width", 140)
    cols = ["faers_name", "drugbank_id", "drugbank_name", "matched"]
    print(f"\n--- Sample ({len(sample)} of {len(subset):,}) ---\n")
    print(sample[cols].to_string(index=False))
    print()


def search_drug(df: pd.DataFrame, names: dict, query: str):
    q = query.lower()
    mask = df["faers_name"].str.lower().str.contains(q, na=False)

    # Also search by DrugBank name
    df_with_names = df.copy()
    df_with_names["drugbank_name"] = df_with_names["drugbank_id"].map(
        lambda x: names.get(x, "") if pd.notna(x) else ""
    )
    mask |= df_with_names["drugbank_name"].str.lower().str.contains(q, na=False)

    hits = df_with_names[mask]
    if len(hits) == 0:
        print(f"No matches for '{query}'.")
        return

    print(f"\n--- Search: '{query}' ({len(hits)} hits) ---\n")
    pd.set_option("display.max_colwidth", 50)
    pd.set_option("display.width", 150)
    cols = ["faers_name", "drugbank_id", "drugbank_name", "matched"]
    print(hits[cols].to_string(index=False))
    print()


def export_unmatched(df: pd.DataFrame, path: str):
    unmatched = df[~df["matched"]].sort_values("faers_name")
    unmatched.to_csv(path, index=False)
    print(f"Exported {len(unmatched):,} unmatched drugs to {path}")


def main():
    parser = argparse.ArgumentParser(description="Verify DrugBank-FAERS canonicalization")
    parser.add_argument("--sample", type=int, default=30)
    parser.add_argument("--matched", action="store_true", help="Show only matched drugs")
    parser.add_argument("--unmatched", action="store_true", help="Show only unmatched drugs")
    parser.add_argument("--search", type=str, default=None)
    parser.add_argument("--export", type=str, default=None,
                        help="Export unmatched drugs to CSV")
    parser.add_argument("--details", type=str, default=str(DETAILS_PATH))
    args = parser.parse_args()

    df = load_details(Path(args.details))
    names = load_names()
    print_summary(df, names)

    if args.search:
        search_drug(df, names, args.search)
    elif args.export:
        export_unmatched(df, args.export)
    else:
        matched_filter = None
        if args.matched:
            matched_filter = True
        elif args.unmatched:
            matched_filter = False
        print_sample(df, names, n=args.sample, matched_only=matched_filter)


if __name__ == "__main__":
    main()
